Clone page
Maryjanee/Embedding-Images-and-Videos pull request #1
Opened 2020-06-03 15:52 UTC by Maryjanee

Please Review our code on the project: Embedding images and videos.

2020-06-04 02:04 UTC, sumancrest0001 reviewed
**Status: Changes required
Hello TEAM :wave:** 
You have done a nice job to create an almost similar layout, the readme file is also looking good. But there are some minor issues that need to be addressed before moving ahead. let's fix them.
[Required] The YouTube button on the left should align with other contents. Currently, they are not aligned properly. :point_down: 
![Screenshot from 2020-06-04 07-41-49](https://user-images.githubusercontent.com/37747619/83706593-9a475680-a637-11ea-9203-a380969ee13f.png)
It should be :point_down: 
![Screenshot from 2020-06-04 07-47-37](https://user-images.githubusercontent.com/37747619/83706626-b3e89e00-a637-11ea-813e-91976b17ed0a.png)

[Optional] You can change the logo also to give it similar looks.

2020-06-04 02:25 UTC, sumancrest0001 commented on index.html
> +                </ul>
[Required] Share icon should be a button but it is an item only in your layout. [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) of the requirement.

[Required] Thumbnail images of other videos are not showing.I am using [githack](https://raw.githack.com/) to check the project.  Have a look :point_down: 
![Screenshot from 2020-06-04 07-37-30](https://user-images.githubusercontent.com/37747619/83707912-ddef8f80-a63a-11ea-9b6b-b6829cf5cd23.png)

2020-06-04 02:28 UTC, sumancrest0001 requested changes
**Kindly make the requested changes and request another review.**

If you have any queries regarding the review or need support, message me on slack **Suman Shrestha**. I am happy to help you.
**Happy coding !!!**

2020-06-04 09:12 UTC, rahalrazika commented
All changes requested have been done and the readme file has been updated with a live demo of the project.

2020-06-05 00:37 UTC, elmejdki commented
### Pull request under review by Zakariae El Mejdki.

2020-06-05 01:20 UTC, elmejdki requested changes
# Great job so far team :woman_technologist: :tophat: 
### status: require changes

- Add a meaningful title and summary on your pull request, you can use on the title *Completed Youtube clone project*, and on the summary try to add some bullet point of what you have accomplished, 

- use this link [HTLM validator](https://validator.w3.org/#validate_by_uri) to validate your HTML code, while validating it I have found the following errors:

![image](https://user-images.githubusercontent.com/34653764/83825622-b992c200-a6d1-11ea-8786-6fd6f7206778.png)
- To fix this error please remove any HTML styling attributes and use CSS instead. 

![image](https://user-images.githubusercontent.com/34653764/83825722-155d4b00-a6d2-11ea-8a79-5b9129c9c9ed.png)
- to fix this one also you need to add a heading and then use a display none in your CSS, to make it invisible.

### please make the required changes before requesting another pull request
_if you have any question be free to contact me on slack you will find me as **Zakariae El Mejdki**_

2020-06-05 01:20 UTC, elmejdki commented on README.md
> +- Github: [@rahalrazika](https://github.com/rahalrazika)
[OPTIONAL] if it is possible add also your Linkedin and Twitter profile links here.

2020-06-05 01:20 UTC, elmejdki commented on style.css
> +/* Basic resets */
kindly remove all the comments from all the files:
![image](https://user-images.githubusercontent.com/34653764/83825179-7b48d300-a6d0-11ea-852c-3d54ac4bc2ff.png)

2020-06-05 01:20 UTC, elmejdki commented on style.css
> +/* aside styles */
remove this comment also.

2020-06-05 01:20 UTC, elmejdki commented on style.css
> +/* Video-container */
also this one.

2020-06-05 01:20 UTC, elmejdki commented on style.css
> +/*Main Styles */
and this one.

2020-06-05 01:20 UTC, elmejdki commented on style.css
> +/* Form Styles */
another comment to be deleted.

2020-06-05 01:20 UTC, elmejdki commented on style.css
> +/* General styles */
remove this comment as suggested above.

2020-06-05 01:20 UTC, elmejdki commented on style.css
> +/* Navigation Styles */
and this one.

2020-06-05 08:49 UTC, Maryjanee commented
- Added navigation bar
- Embedded Video and videos on webpage
- Added sidebar with recommended images.
- Removed the comments in the css file
- Validated index File with HTML validator and fixed all resulting issues.

2020-06-05 12:14 UTC, HADDADSOHAIB requested changes
> ### Pull Request under the review by Sohaib Haddad. (TSE)
### Change Required :recycle: 

### Hello @Maryjanee and @rahalrazika     :handshake: 

### You did wonderful job :clap:  your project is looking good :medal_sports: and look like the original. 

### You implemented the changes required by the previous TSE, good job, however I found some issues while checking your project latest version using https://raw.githack.com/, (the live demo provided in the readme is ok), there are some changes to get the project approved :point_down:
- the thumbnails are not showing, check the comments for suggesting.
![Screenshot from 2020-06-05 13-06-44](https://user-images.githubusercontent.com/26064042/83874875-13c17080-a72e-11ea-96e5-15eb4e99a27a.png)
 ### Please fix these issues and asked for another code review.

2020-06-05 12:14 UTC, HADDADSOHAIB commented on index.html
> +            <img src="images/1.png" alt="thumbnail_1" />
I see that the name of your file in the image folder is 1.PNG, that could be the issue why the images are not showing

2020-06-05 22:15 UTC, BrittanyBlake commented
### Pull Request Under Review by Brittany Blake (TSE)

2020-06-05 22:29 UTC, BrittanyBlake approved these changes
### Status: Approved ✅
****
### Hi @Maryjanee and @rahalrazika 👋 👋 
You have done a great job implementing the changes requested by the previous TSEs! 👍 
### Congratulations 🏅 👏 
Go ahead and merge this pull request and move on to the next project 💪 

HAPPY CODING! 👩🏾‍💻

2020-06-05 23:01 UTC, merged